## note
- 抛出异常会改变程序的执行流程，假如在`try`之后需要释放之前语句获取的资源或数据库连接，此时则可能造成资源无法释放，使用`finally`块可以解决此问题。即使读取文件时发生异常，`finally`块也能保证块中的语句得到执行。（也可以通过使用`using`语句解决此问题）